version: '3.8'

services:
  # Servicio de la base de datos PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_nest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: prueba-tecnica
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
